GET http://localhost:8080/webapi/ordenador


#######

GET http://localhost:8080/webapi/ordenador?modelo=Optimus


#######


GET http://localhost:8080/webapi/ordenador?marca=apple

######

POST http://localhost:8080/webapi/ordenador
content-type: application/json

{
    "modelo":"Hola",
    "marca":"apple",
    "precio":"5800.00",
    "numserie":"GGt09"
}

######

POST http://localhost:8080/webapi/ordenador
content-type: application/json

{
    "modelo":"Ultimo",
    "marca":"Axus",
    "precio":"450.45",
    "numserie":"878AA"
}

######
DELETE http://localhost:8080/webapi/ordenador/FT21R

######

GET http://localhost:8080/webapi/ordenador


######

POST http://localhost:8080/webapi/ordenador
content-type: application/json

{
    "modelo":"Nuevo3",
    "marca":"Axus",
    "precio":"300.95",
    "numserie":"DD33EE"
}


